version: '3.8'

services:
  testservice-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ../src:/app/src:ro
    ports:
      - "5000:8080"
    
  # Development tools
  seq:
    image: datalust/seq:latest
    container_name: testservice-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    networks:
      - testservice-network
    restart: unless-stopped

  # Grafana for monitoring dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: testservice-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - testservice-network
    restart: unless-stopped

volumes:
  grafana-data: